/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package globalproject.ui;
import globalproject.BaseWindows;
import globalproject.domain.Cliente;
import globalproject.domain.ClientsRepository;
import java.util.ArrayList;
/**
 *
 * @author alumno
 */
public class ClientsUI extends BaseWindows {

      private ClientsRepository repository;
    /**
     * Creates new form ClientsUI
     */
    public ClientsUI() {
        initComponents();
    }
    
      @Override
    protected void  initUI(){
        ArrayList<Cliente> lista = (ArrayList<Cliente>) this.repository.getAll();
        
        
        StringBuilder sb = new StringBuilder();
        
        String cliCodeTitle = "Codigo Clientes";
        String cliNameTitle = "Nombre Empresa";
        String cliRubroTitle = "Rubro";
        sb.append(cliCodeTitle+"\t\t" + cliNameTitle +"\t\t" + cliRubroTitle +"\r\n");
        
        for (int i = 0; i < lista.size(); i++) {
            
            String cliCode = lista.get(i).getCliId();
            String cliName = lista.get(i).getCliNombre();
            String cliRubro = lista.get(i).getCliRubro();
            
            sb.append(cliCode+"\t\t" + cliName +"\t\t" + cliRubro +"\r\n");
            sb.append("\r\n");
        }
        productsui_lbl_list.setText(sb.toString());
    }
     public void setRepository(ClientsRepository repository) {
        this.repository = repository;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productsui_lbl_list = new javax.swing.JTextArea();
        producstui_lbl_title = new javax.swing.JLabel();

        productsui_lbl_list.setColumns(20);
        productsui_lbl_list.setRows(5);
        jScrollPane1.setViewportView(productsui_lbl_list);

        producstui_lbl_title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        producstui_lbl_title.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(producstui_lbl_title)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(producstui_lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel producstui_lbl_title;
    private javax.swing.JTextArea productsui_lbl_list;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
