/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package globalproject.ui;

import globalproject.BaseWindows;
import globalproject.domain.Product;
import globalproject.domain.ProductsRepository;
import java.util.ArrayList;

/**
 *
 * @author joseflavio
 */
public class ProductsUi extends BaseWindows {

    private ProductsRepository repository;
   
    /**
     * Creates new form ProductsUI
     */
    public ProductsUi() {
        initComponents();
    }
    
    @Override
    protected void initUI() {
        ArrayList<Product> lista = (ArrayList<Product>) this.repository.getAll();
        
        StringBuilder sb = new StringBuilder();
        
        String prodCodeTitle = "Cod Producto";
        String prodNameTitle = "Product Name";
        String prodPriceTitle = "Product Price";
        sb.append(prodCodeTitle+"\t\t" + prodNameTitle +"\t\t" + prodPriceTitle +"\r\n");
        
        for (int i = 0; i < lista.size(); i++) {
            
            String prodCode = lista.get(i).getProdCode();
            String prodName = lista.get(i).getProdName();
            String prodPrice = String.valueOf(lista.get(i).getProdPrice());
            
            sb.append(prodCode+"\t\t" + prodName +"\t\t" + prodPrice +"\r\n");
            sb.append("\r\n");
        }
        productsui_lbl_list.setText(sb.toString());
        
    }
    
    public void setRepository(ProductsRepository repository) {
        this.repository = repository;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        producstui_lbl_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsui_lbl_list = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        producstui_lbl_title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        producstui_lbl_title.setText("Productos");

        productsui_lbl_list.setColumns(20);
        productsui_lbl_list.setRows(5);
        jScrollPane1.setViewportView(productsui_lbl_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(producstui_lbl_title)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(producstui_lbl_title)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel producstui_lbl_title;
    private javax.swing.JTextArea productsui_lbl_list;
    // End of variables declaration//GEN-END:variables

}
