package globalproject.ui;

import globalproject.BaseWindows;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author Jose Flavio
 */
public final class Welcome extends BaseWindows {

    private String selectedLanguageCode = "es";

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        log("Welcome windows... init components");
        initComponents();
        initUI();
        welcome_cb.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                switch(welcome_cb.getSelectedIndex()){
                    case 0: {
                        selectedLanguageCode = "en";
                        log("language: " + selectedLanguageCode);
                        changeLanguage(selectedLanguageCode);
                        initUI();
                        break;
                    }

                    case 1: {
                        selectedLanguageCode = "es";
                        log("language: " + selectedLanguageCode);
                        changeLanguage(selectedLanguageCode);
                        initUI();
                        break;
                    }
                }
                
            }
            
        });
    }

    @Override
    protected void initUI() {
        
      welcome_lbl_title.setText(strings.getString("welcome_lbl_title"));
      welcome_lbl_desc.setText(strings.getString("welcome_lbl_description"));
      welcome_btn.setText(strings.getString("welcome_btn_enter"));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_lbl_title = new javax.swing.JLabel();
        welcome_lbl_desc = new javax.swing.JLabel();
        welcome_cb = new javax.swing.JComboBox<>();
        welcome_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome_lbl_title.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        welcome_lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_lbl_title.setText("Bienvenido al sistema de StorageData");

        welcome_lbl_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_lbl_desc.setText("Por favor, escoge tu idioma:");

        welcome_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Español" }));

        welcome_btn.setText("Entrar");
        welcome_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcome_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcome_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(welcome_cb, 0, 137, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(welcome_lbl_desc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(welcome_lbl_title)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(welcome_lbl_title)
                .addGap(35, 35, 35)
                .addComponent(welcome_lbl_desc)
                .addGap(18, 18, 18)
                .addComponent(welcome_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcome_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void welcome_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcome_btnActionPerformed
        Menu menu = new Menu();
        dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_welcome_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton welcome_btn;
    private javax.swing.JComboBox<String> welcome_cb;
    private javax.swing.JLabel welcome_lbl_desc;
    private javax.swing.JLabel welcome_lbl_title;
    // End of variables declaration//GEN-END:variables

}
